=== api-evangelist/amazon-mediaconvert/json-schema/mediaconvert-api-create-job-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-mediaconvert/refs/heads/main/json-schema/mediaconvert-api-create-job-request-schema.json",
  "title": "CreateJobRequest",
  "description": "CreateJobRequest schema from Amazon MediaConvert API",
  "type": "object",
  "properties": {
    "AccelerationSettings": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AccelerationSettings"
        },
        {
          "xml": {
            "name": "accelerationSettings"
          },
          "description": "Optional. Accelerated transcoding can significantly speed up jobs with long, visually complex content. Outputs that use this feature incur pro-tier pricing. For information about feature limitations, see the AWS Elemental MediaConvert User Guide."
        }
      ]
    },
    "BillingTagsSource": {
      "allOf": [
        {
          "$ref": "#/components/schemas/BillingTagsSource"
        },
        {
          "xml": {
            "name": "billingTagsSource"
          },
          "description": "Optional. Choose a tag type that AWS Billing and Cost Management will use to sort your AWS Elemental MediaConvert costs on any billing report that you set up. Any transcoding outputs that don't have an associated tag will appear in your billing report unsorted. If you don't choose a valid value for this field, your job outputs will appear on the billing report unsorted."
        }
      ]
    },
    "ClientRequestToken": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "xml": {
            "name": "clientRequestToken"
          },
          "description": "Prevent duplicate jobs from being created and ensure idempotency for your requests. A client request token can be any string that includes up to 64 ASCII characters. If you reuse a client request token within one minute of a successful request, the API returns the job details of the original request instead. For more information see https://docs.aws.amazon.com/mediaconvert/latest/apireference/idempotency.html."
        }
      ]
    },
    "HopDestinations": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__listOfHopDestination"
        },
        {
          "xml": {
            "name": "hopDestinations"
          },
          "description": "Optional. Use queue hopping to avoid overly long waits in the backlog of the queue that you submit your job to. Specify an alternate queue and the maximum time that your job will wait in the initial queue before hopping. For more information about this feature, see the AWS Elemental MediaConvert User Guide."
        }
      ]
    },
    "JobTemplate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "xml": {
            "name": "jobTemplate"
          },
          "description": "Optional. When you create a job, you can either specify a job template or specify the transcoding settings individually."
        }
      ]
    },
    "Priority": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__integerMinNegative50Max50"
        },
        {
          "xml": {
            "name": "priority"
          },
          "description": "Optional. Specify the relative priority for this job. In any given queue, the service begins processing the job with the highest value first. When more than one job has the same priority, the service begins processing the job that you submitted first. If you don't specify a priority, the service uses the default value 0."
        }
      ]
    },
    "Queue": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "xml": {
            "name": "queue"
          },
          "description": "Optional. When you create a job, you can specify a queue to send it to. If you don't specify, the job will go to the default queue. For more about queues, see the User Guide topic at https://docs.aws.amazon.com/mediaconvert/latest/ug/what-is.html."
        }
      ]
    },
    "Role": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "xml": {
            "name": "role"
          },
          "description": "Required. The IAM role you use for creating this job. For details about permissions, see the User Guide topic at the User Guide at https://docs.aws.amazon.com/mediaconvert/latest/ug/iam-role.html."
        }
      ]
    },
    "Settings": {
      "allOf": [
        {
          "$ref": "#/components/schemas/JobSettings"
        },
        {
          "xml": {
            "name": "settings"
          },
          "description": "JobSettings contains all the transcode settings for a job."
        }
      ]
    },
    "SimulateReservedQueue": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SimulateReservedQueue"
        },
        {
          "xml": {
            "name": "simulateReservedQueue"
          },
          "description": "Optional. Enable this setting when you run a test job to estimate how many reserved transcoding slots (RTS) you need. When this is enabled, MediaConvert runs your job from an on-demand queue with similar performance to what you will see with one RTS in a reserved queue. This setting is disabled by default."
        }
      ]
    },
    "StatusUpdateInterval": {
      "allOf": [
        {
          "$ref": "#/components/schemas/StatusUpdateInterval"
        },
        {
          "xml": {
            "name": "statusUpdateInterval"
          },
          "description": "Optional. Specify how often MediaConvert sends STATUS_UPDATE events to Amazon CloudWatch Events. Set the interval, in seconds, between status updates. MediaConvert sends an update at this interval from the time the service begins processing your job to the time it completes the transcode or encounters an error."
        }
      ]
    },
    "Tags": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__mapOf__string"
        },
        {
          "xml": {
            "name": "tags"
          },
          "description": "Optional. The tags that you want to add to the resource. You can tag resources with a key-value pair or with only a key.  Use standard AWS tags on your job for automatic integration with AWS services and for custom integrations and workflows."
        }
      ]
    },
    "UserMetadata": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__mapOf__string"
        },
        {
          "xml": {
            "name": "userMetadata"
          },
          "description": "Optional. User-defined metadata that you want to associate with an MediaConvert job. You specify metadata in key/value pairs.  Use only for existing integrations or workflows that rely on job metadata tags. Otherwise, we recommend that you use standard AWS tags."
        }
      ]
    }
  },
  "required": [
    "Role",
    "Settings"
  ]
}

=== api-evangelist/amazon-mediaconvert/examples/mediaconvert-api-create-job-request-example.json
{
  "AccelerationSettings": "example-value",
  "BillingTagsSource": "example-value",
  "ClientRequestToken": "example-value",
  "HopDestinations": "example-value",
  "JobTemplate": "example-value",
  "Priority": "example-value",
  "Queue": "example-value",
  "Role": "example-value",
  "Settings": "example-value",
  "SimulateReservedQueue": "example-value",
  "StatusUpdateInterval": "ACTIVE",
  "Tags": "example-value",
  "UserMetadata": "example-value"
}
